-- 코드를 작성해주세요
SELECT A.ID, IFNULL(CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN (SELECT PARENT_ID, COUNT(PARENT_ID) CNT
           FROM ECOLI_DATA
           GROUP BY PARENT_ID) AS B
ON A.ID = B.PARENT_ID
ORDER BY A.ID