-- 코드를 작성해주세요
SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
LEFT JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH)
       FROM FISH_INFO AS A
       WHERE A.FISH_TYPE = FI.FISH_TYPE
       GROUP BY A.FISH_TYPE)
ORDER BY FI.ID




